superfaceai/station

README.md

Fixes for readme:
- CI/CD badge
- Superface Logo

Fix CI/CD badge and Logo in Readme

---

.github/pull_request_template.md
CONTRIBUTING.md
CONVENTIONS.md
capabilities/communication/send-email/profile.supr

This improves contributing guides and adds conventions.
Also `commmunication/send-email` was updated to follow the conventions except One usecase per Profile. I will do that as separate PR, as it is bigger change not entirely needed for conventions.
We want to have capabilities in great state and set role model for others how they could be written.
Focused mainly on [CONVENTIONS.md](https://github.com/superfaceai/station/pull/62/files#diff-2e28754e69aa417e5b6d89e99e42f05bfb6330800fa823753383db1d170fbc2f). There is more work to be done to make the repository play nice with all the tooling.

Contributing and conventions

---

capabilities/weather/current-city/maps/mock.suma

Fix profile name in mock provider

---

capabilities/weather/current-city/profile.supr

- Adjust title to mention weather
- Add examples for city field, description
Current profile title omits mentioning that this is actually about weather.
- documentation

docs(weather/current-city): Improve descriptions

---

.eslintrc.js
.github/ISSUE_TEMPLATE/BUG_TEMPLATE.md
.github/ISSUE_TEMPLATE/QUESTION_TEMPLATE.md
.prettierignore
capabilities/address/geocoding/maps/azure-maps.test.ts
capabilities/weather/current-city/maps/current-city.ts
capabilities/weather/current-city/maps/mock.test.ts
capabilities/weather/current-city/maps/wttr-in.test.ts

This PR updates lint and format settings to not touch generated files.

chore: ignore generated files in lint and format

---

package.json
src/util.test.ts
src/util.ts
src/validate.test.ts
yarn.lock

This PR updates @superfaceai/cli to version 0.0.25 and @superfaceai/one-sdk to version 0.0.36
@superfaceai/one-sdk 0.0.36 introduced breaking changes that had to be fixed in this PR. `Profile` definition has been changed and `SuperJsonDocument` has been moved to @superfaceai/ast.

Update superface one-sdk and cli dependencies

---

capabilities/communication/send-email/maps/__snapshots__/mailchimp.test.ts.snap
capabilities/communication/send-email/maps/mailchimp.suma
capabilities/communication/send-email/maps/mailchimp.test.ts
capabilities/communication/send-templated-email/maps/__snapshots__/mailchimp.test.ts.snap
capabilities/communication/send-templated-email/maps/mailchimp.suma
capabilities/communication/send-templated-email/maps/mailchimp.test.ts
nock/communication/send-email/mailchimp/SendEmail/recording.json
nock/communication/send-templated-email/mailchimp/SendTemplatedEmail/recording.json
providers/mailchimp.json
superface/super.json

I just learnt we already support apikey in body. So integration parameter isn't needed.

Use apikey in body for mailchimp

---

package.json

This will ensure that at least some value is used. `.env.capabilities.example` should be always working with tests in repository.

Load example env file for tests

---

capabilities/weather/current-city/maps/wttr-in.suma

Silence the VSCode extension error in `wttr-in.suma`:

chore(weather/current-city/wttr-in): Silence error

---

capabilities/communication/email-templates/maps/sendgrid.suma

Found out I am using mapped error, which is not defined in profile. The mapped error isn't that much helpful right now, as I am not using it for many other occasions.

Do not use mapped error in Sendgrid map

---

capabilities/communication/send-sms/maps/__snapshots__/tyntec.test.ts.snap
capabilities/communication/send-sms/maps/tyntec.suma
capabilities/communication/send-sms/maps/tyntec.test.ts

- fixed error mapping in Tyntect map

Send SMS Tyntect wrong Error mapping

---

nock/address/geocoding/nominatim/Geocode/recording-445453e2eeb4b458e12abdd76e5503c5.json
nock/address/geocoding/nominatim/Geocode/recording-99914b932bd37a50b983c5e7c90ae93b.json
nock/address/geocoding/nominatim/ReverseGeocode/recording-43d32a6d35d8e93e72165e5d0b949e2a.json
nock/address/geocoding/nominatim/ReverseGeocode/recording-99914b932bd37a50b983c5e7c90ae93b.json
providers/nominatim.json

This PR fixes Nominatim base path. / at the end of the base path was removed.

fix: nominatim base path

---

capabilities/language/translate/profile.supr

This PR adds examples to  `language/translate` profile and bumps profile version to `1.0.1`.
I propose to read the PR by commits.
Rendered examples:

Add `language/translate` profile examples

---

capabilities/language/analyze-plain-text-sentiment/profile.supr

This PR adds `language/analyze-plain-text-sentiment` profile examples and bumps profile version to `1.0.1`.
Rendered examples:

Add `language/analyze-plain-text-sentiment` profile examples

---

capabilities/speech/synthesis/profile.supr

This PR adds `speech/synthesis` profile examples and bumps profile version to `1.0.1`
The response contains synthesized audio bytes, therefore is in  the result example text description of the output.

Add `speech/synthesis` profile examples

---

capabilities/weather/current-city/profile.supr

Adding simple examples for `weather/current-city` capability.
Looks like this when renderer

feat: Adding examples to `weather/current-city`

---

capabilities/address/geocoding/profile.supr

Adding simple examples for `address/geocoding` capability.
Looks like this when renderer

feat: Adding examples to `address/geocoding`

---

capabilities/address/clean-address/profile.supr

Adding simple examples for `address/clean address` capability.
I basically took the JSON examples that were previously present in the the use case description. Because of this, I also took the liberty of slightly modifying the description to be human readable only. Let me know if you disapprove of this.
Looks like this when rendered:

feat: Adding examples to `address/clean-address`

---

capabilities/communication/send-message/profile.supr

Adding simple examples for `communication/send-message` capability. Also fixed typo in result `destination` title. It used four quote marks with resulted in title equal to `"`.
Looks like this when rendered

feat: Adding examples `communication/send-message`

---

capabilities/communication/send-templated-email/profile.supr

Adding simple examples for `communication/send-templated-email` capability
Looks like this when rendered

feat: Adding examples to `communication/send-templated-email`

---

capabilities/communication/send-email/profile.supr

Adding simple examples for `communication/send-email` capability
Looks like this when rendered

feat: Adding examples to `communication/send-email`

---

capabilities/communication/send-sms/profile.supr

Adding simple examples for `communication/send-sms` capability
Looks like this when rendered

feat: Adding examples to `communication/send-sms`

---

capabilities/computer-vision/face-detection/profile.supr

This PR adds basic examples to computer-vision/face-detection capability.

chore: add examples to face detection capability

---

capabilities/address/geocoding/profile.supr

Only minor changes in doc strings as requested by @lirakinay.
- Fixed and added articles.
- Added missing dots at some places.

fix(address/geocoding): Grammar in profile docs

---

grid/computer-vision/face-detection/profile.supr
grid/crm/contacts/profile.supr
grid/navigation/nearby-poi/profile.supr
grid/social-media/publishing-profiles/profile.supr
package.json
yarn.lock

Updates CLI and fixes examples in profiles to be valid.
New release of CLI

chore: bump @superfaceai/cli from 1.0.1 to 1.1.0

---

grid/social-media/followers/profile.supr
grid/social-media/posts-lookup/profile.supr
grid/social-media/posts/profile.supr
grid/social-media/publish-post/profile.supr
grid/social-media/publishing-profiles/profile.supr

Update documentation for social media profiles:
- Add missing description of the profiles
- Deduplicate fields in lookup profile
- Clearer terms, grammar fixes etc.
Nicer catalog preview.

docs(social-media): Improve profiles documentation

---

grid/computer-vision/face-detection/maps/mock.suma

Updated mock result to serve some real data.

fix: use real data for mock result (same as example)

---

grid/communication/send-sms/profile.supr

fix: typo in sms profile

---

grid/project-management/projects/profile.supr
grid/project-management/tasks/profile.supr

Add descriptions, remove periods, shorten titles.
Looks less out of place in the catalog.
Previous:

update project-management docstrings to match catalog

---

grid/vcs/pull-requests/maps/bitbucket.suma
grid/vcs/pull-requests/maps/github.suma
grid/vcs/pull-requests/maps/gitlab.suma
grid/vcs/user-repos/maps/bitbucket.suma
grid/vcs/user-repos/maps/github.suma
grid/vcs/user-repos/maps/gitlab.suma

This PR fixes problem with allocation of large size Array during pagination.
Fixes: https://github.com/superfaceai/station/issues/266

fix(vcs): Smaller array size in pagination hack

---

grid/social-media/replies/profile.supr

Adds a forgotten docstring on the *profile* containing the `GetPostReplies` use case; also generalizes the docstring on the use case.

add docstring to `social-media/replies` profile

---

grid/project-management/projects/profile.supr
grid/project-management/tasks/profile.supr
grid/social-media/replies/profile.supr

Forgot to bump patch versions on `project-management` and `social-media/replies` profiles while updating docstrings, this PR fixes it.

bump patch versions to update docstrings

---

README.md

fix typos & language in README

---

grid/chat/channels/profile.supr
grid/chat/messages/profile.supr
grid/chat/send-message/profile.supr
grid/communication/email-templates/profile.supr
grid/computer-vision/face-detection/profile.supr
grid/crm/contacts/profile.supr
grid/crypto/exchange-rate/exchange-rate.supr
grid/language/translate/profile.supr
grid/navigation/nearby-poi/maps/overpass-de.suma
grid/navigation/nearby-poi/profile.supr
grid/oauth2/refresh-token/profile.supr
grid/weather/current-city/profile.supr
grid/weather/forecast-city/profile.supr

Miscellaneous fixes of public profile descriptions (periods at the end of descriptions, capitalization, language fixes, missing docstrings)

Chore: fix catalog descriptions

---

CONVENTIONS.md

This PR adds mention of profile examples to conventions.

Add examples to CONVENTIONS.md

---

grid/recruitment/list-stage-changes/maps/__snapshots__/breezy-hr.test.ts.snap
grid/recruitment/list-stage-changes/maps/__snapshots__/workable.test.ts.snap
grid/recruitment/list-stage-changes/maps/breezy-hr.suma
grid/recruitment/list-stage-changes/maps/breezy-hr.test.ts
grid/recruitment/list-stage-changes/maps/list-stage-changes.ts
grid/recruitment/list-stage-changes/maps/mock.suma
grid/recruitment/list-stage-changes/maps/mock.test.ts
grid/recruitment/list-stage-changes/maps/recordings/breezy-hr.recording.json
grid/recruitment/list-stage-changes/maps/recordings/workable.recording.json
grid/recruitment/list-stage-changes/maps/workable.suma
grid/recruitment/list-stage-changes/maps/workable.test.ts
grid/recruitment/list-stage-changes/profile.supr
superface/super.json

This PR renames profile, use case and subsequent maps.
- from `recruitment/get-stage-changes` to `recruitment/list-stage-changes`
- from `GetStageChanges` to `ListStageChanges`
Naming conventions.

feat: Rename profile `recruitment/get-stage-changes`

---

grid/recruitment/list-companies/maps/__snapshots__/breezy-hr.test.ts.snap
grid/recruitment/list-companies/maps/breezy-hr.suma
grid/recruitment/list-companies/maps/breezy-hr.test.ts
grid/recruitment/list-companies/maps/list-companies.ts
grid/recruitment/list-companies/maps/recordings/breezy-hr.recording.json
superface/super.json

Adds new map for profile `recruitment/list-companies`
ATS integrations

feat: Add `ListCompanies` map for provider `breezy-hr`

---

grid/project-management/tasks/maps/mock.suma
package.json
yarn.lock

Update OneSDK to latest version.
Also fixed mock implementation where result was mapped even though profile didn't specify any.
I want to run station latest available OneSDK version.

Update OneSDK to 2.2.0

---

grid/recruitment/list-candidates/maps/__snapshots__/mock.test.ts.snap
grid/recruitment/list-candidates/maps/mock.suma
grid/recruitment/list-candidates/maps/mock.test.ts
grid/recruitment/list-candidates/profile.supr
recordings/recruitment/list-candidates/mock.recording.json
superface/super.json

This PR adds profile `recruitment/list-candidates` with mock map.
`recruitment/list-candidates` is used in CV Analyzer example app and inquired by some of our leads.

Add `recruitment/list-candidates` profile

---

grid/recruitment/update-candidate/maps/__snapshots__/mock.test.ts.snap
grid/recruitment/update-candidate/maps/mock.suma
grid/recruitment/update-candidate/maps/mock.test.ts
grid/recruitment/update-candidate/maps/recordings/mock.recording.json
grid/recruitment/update-candidate/profile.supr
superface/super.json

This PR adds `recruitment/update-candidate` profile and `mock` map.
The `recruitment/update-candidate` profile will be used in by CV Analyzer example app.

Add `recruitment/update-candidate` profile and `mock` map

---

grid/recruitment/create-lead/profile.supr

This PR fixes  `recruitment/create-lead` profile description.

Fix `recruitment/create-lead` profile description

---

grid/recruitment/create-candidate/maps/__snapshots__/breezy-hr.test.ts.snap
grid/recruitment/create-candidate/maps/__snapshots__/workable.test.ts.snap
grid/recruitment/create-candidate/maps/create-candidate.ts
grid/recruitment/update-candidate/maps/__snapshots__/workable.test.ts.snap
grid/recruitment/update-candidate/maps/update-candidate.ts

Fixes `create-candidate` tests:
- use `expect(() => result.unwrap()).toThrow()` instead of just testing for `isOk()` to provide better errors
- actually check for error codes of expected errors

fix: ATS tests

---

grid/recruitment/list-jobs/maps/__snapshots__/greenhouse.test.ts.snap
grid/recruitment/list-jobs/maps/greenhouse.suma
grid/recruitment/list-jobs/maps/greenhouse.test.ts
grid/recruitment/list-jobs/maps/recordings/greenhouse.recording.json
superface/super.json

feat: add ListJobs map for greenhouse

---

grid/recruitment/list-jobs/profile.supr

This PR fixes confusing description of `recruitment/list-jobs` profile.

Fix `recruitment/list-jobs` profile description

---

grid/address/geocoding/maps/__snapshots__/azure-maps.test.ts.snap
grid/address/geocoding/maps/__snapshots__/google-apis-maps.test.ts.snap
grid/address/geocoding/maps/__snapshots__/here.test.ts.snap
grid/address/geocoding/maps/__snapshots__/nominatim.test.ts.snap
grid/address/geocoding/maps/__snapshots__/opencage.test.ts.snap
grid/address/geocoding/maps/__snapshots__/tomtom.test.ts.snap
grid/chat/members/maps/members.ts
package.json
yarn.lock

- updates Parser to 2.1.0
- updates AST to 1.3.0
- updates OneSDK to 2.3.0
- updates Testing to 4.0.0
-  prepares maps which could be failing with new OneSDK 2.3.0
Requires https://github.com/superfaceai/station/pull/354

Prepare for OneSDK 2.3.0

---

grid/chat/channels/profile.supr
grid/chat/members/profile.supr
grid/chat/messages/profile.supr
grid/chat/send-message/profile.supr
grid/chat/threads/profile.supr

All chat use cases are missing safety definition, which implicitly declares them as unsafe.
I'd like to use these use cases in OneService, but they end up as mutations instead of queries.

fix(chat/*): Specify usecases' safety

---

.github/workflows/ci_cd.yml

Hopefully also runs CI/CD pipeline for outside collaborators' pull requests (e.g. #363)
Going forward, we may expect more PRs that do not originate from the origin `superfaceai/station` repo.

fix: run CI/CD pipeline for public fork pull requests

---

grid/recruitment/get-cv/maps/__snapshots__/greenhouse.test.ts.snap
grid/recruitment/get-cv/maps/greenhouse.suma
grid/recruitment/get-cv/maps/greenhouse.test.ts
grid/recruitment/get-cv/maps/recordings/greenhouse.recording.json
superface/super.json

This PR adds recruitment/get-cv use case impl for greenhouse provider

feat: add recruitment/get-cv for greenhouse

---

grid/address/clean-address/profile.supr
grid/address/geocoding/profile.supr

Add missing safety information for address/geocoding and address/clean-address profiles.
We need this for OneService, currently these use cases appear as mutations.

fix(address): Specify usecases' safety

---

.prettierignore

Adds `.ast.json` files to `.prettierignore`
They're already in `.gitignore` and don't need to be formatted prettily, slowing down the formatting task.

chore: add ASTs to .prettierignore
